"""Ajout du champ prenom dans le model Client + transfomré adresse_id en str 36

Revision ID: 34a93a8e63ac
Revises: ab7f3e28ed12
Create Date: 2025-07-28 17:33:25.994006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a93a8e63ac'
down_revision = 'ab7f3e28ed12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=False))
        batch_op.alter_column('adresse_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('adresse_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
