"""Initial migration

Revision ID: 71bc6aed9dc8
Revises: b52969beb88b
Create Date: 2025-07-25 13:29:30.023052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bc6aed9dc8'
down_revision = 'b52969beb88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rue', sa.String(length=200), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=20), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('prix_defaut', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_entreprise', sa.String(length=100), nullable=False),
    sa.Column('ntva', sa.String(length=20), nullable=True),
    sa.Column('siret', sa.String(length=20), nullable=True),
    sa.Column('code_ape', sa.String(length=10), nullable=True),
    sa.Column('nrge', sa.String(length=20), nullable=True),
    sa.Column('travaux_sous_garantie_decennale', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('total_ht', sa.Float(), nullable=False),
    sa.Column('tva_taux', sa.Float(), nullable=True),
    sa.Column('tva_montant', sa.Float(), nullable=True),
    sa.Column('total_ttc', sa.Float(), nullable=True),
    sa.Column('type_document', sa.Enum('DEVIS', 'FACTURE', name='documenttype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('adresse_chantier', sa.String(length=255), nullable=True),
    sa.Column('nom_client', sa.String(length=100), nullable=True),
    sa.Column('email_client', sa.String(length=120), nullable=True),
    sa.Column('telephone_client', sa.String(length=20), nullable=True),
    sa.Column('adresse_client', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('devis_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('description_service', sa.String(length=200), nullable=True),
    sa.Column('reference_snapshot', sa.String(length=50), nullable=True),
    sa.Column('prix_unitaire_snapshot', sa.Float(), nullable=True),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('document')
    op.drop_table('profile')
    op.drop_table('client')
    op.drop_table('service')
    op.drop_table('adresse')
    # ### end Alembic commands ###
