"""Snapshot et TVA

Revision ID: b52969beb88b
Revises: 
Create Date: 2025-07-25 13:07:56.456350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52969beb88b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adresse')
    op.drop_table('service')
    op.drop_table('client')
    op.drop_table('document')
    op.drop_table('profile')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('quantite', sa.INTEGER(), nullable=False),
    sa.Column('prix_unitaire', sa.FLOAT(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom_entreprise', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ntva', sa.VARCHAR(length=20), nullable=True),
    sa.Column('siret', sa.VARCHAR(length=20), nullable=True),
    sa.Column('code_ape', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nrge', sa.VARCHAR(length=20), nullable=True),
    sa.Column('travaux_sous_garantie_decennale', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('adresse_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('type_document', sa.VARCHAR(length=20), nullable=False),
    sa.Column('statut', sa.VARCHAR(length=20), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('adresse_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('prix_defaut', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adresse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rue', sa.VARCHAR(length=200), nullable=False),
    sa.Column('ville', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code_postal', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pays', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
